[package]
name = "evals"
description = "Evaluations for Zed's AI features"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[[bin]]
name = "eval"
path = "src/eval.rs"

[dependencies]
clap.workspace = true
async-compression.workspace = true
anyhow.workspace = true
client.workspace = true
clock.workspace = true
collections.workspace = true
env_logger.workspace = true
fs.workspace = true
futures.workspace = true
futures-batch.workspace = true
git.workspace = true
gpui.workspace = true
language.workspace = true
languages.workspace = true
log.workspace = true
heed.workspace = true
http_client.workspace = true
open_ai.workspace = true
parking_lot.workspace = true
project.workspace = true
settings.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
smol.workspace = true
theme.workspace = true
tree-sitter.workspace = true
util.workspace = true
unindent.workspace = true
worktree.workspace = true
semantic_index.workspace = true
node_runtime.workspace = true
